#include "debug.hpp"
#include "imgui.h"
#include "render_entity.hpp"
#include "runtime.hpp"
#include "sprite.hpp"
#include "timer.hpp"
#include "transformer.hpp"
#include "window.hpp"

using namespace rlge;

class FpsCounter final : public RenderEntity {
public:
    explicit FpsCounter(Scene& scene) : RenderEntity(scene) {}

    void draw() override {
        rq().submitUI([] {
            DrawFPS(10, 10);
        });
    }
};
// Background entity that draws a wide patterned image so movement is obvious.
class Background final : public RenderEntity {
public:
    explicit Background(Scene& scene, Texture2D& texture)
        : RenderEntity(scene)
        , texture_(texture) {}

    void draw() override {
        if (!visible_)
            return;
        // Draw at world origin; the camera moving will reveal different parts.
        rq().submitBackground([this] {
            DrawTexture(texture_, 0, 0, WHITE);
        });
    }

private:
    Texture2D& texture_;
    bool visible_ = true;

    friend class GameScene;
};

// Simple player entity that can move left/right/rotate and is followed by the camera.
class ExampleEntity final : public RenderEntity {
public:
    explicit ExampleEntity(Scene& scene, Texture2D& texture)
        : RenderEntity(scene) {
        auto& tr = add<rlge::Transform>();
        tr.position = {100.0f, 200.0f};

        auto& anim = add<SpriteAnim>(texture, 32, 32);
        anim.loadStrip(0, 4, 0.15f);

        timers_ = &add<TimerComponent>();
        blinkHandle_ = timers_->every(0.35f, [this] { highlight_ = !highlight_; });
        boostCooldown_ = timers_->cooldown(1.5f);
    }

    void update(float dt) override {
        Entity::update(dt);

        const auto& input = scene().input();

        auto* tr = get<rlge::Transform>();
        if (!tr)
            return;

        const bool boostPressed = input.down(rlge::Action::Fire);
        if (boostPressed && timers_->ready(boostCooldown_)) {
            timers_->consume(boostCooldown_);
            boosting_ = true;
            timers_->after(std::chrono::milliseconds(500), [this] { boosting_ = false; });
        }

        const auto currentSpeed = boosting_ ? baseSpeed_ * boostMultiplier_ : baseSpeed_;

        if (input.down(rlge::Action::MoveLeft))
            tr->position.x -= currentSpeed * dt;
        if (input.down(rlge::Action::MoveRight))
            tr->position.x += currentSpeed * dt;
        if (input.down(rlge::Action::MoveUp))
            tr->rotation += currentSpeed * dt;
    }

    void draw() override {
        Entity::draw();

        if (auto* tr = get<rlge::Transform>()) {
            const auto indicatorColor = highlight_ ? ORANGE : YELLOW;
            rq().submitWorld([pos = tr->position, indicatorColor] {
                DrawCircleV(pos + Vector2{0.0f, +36.0f}, 6.0f, indicatorColor);
            });
        }
    }

    [[nodiscard]] bool boostReady() const { return timers_ && timers_->ready(boostCooldown_); }

    bool highlighting() const { return highlight_; }
    bool boosting() const { return boosting_; }

    friend class GameScene;

private:
    float baseSpeed_ = 200.0f;
    float boostMultiplier_ = 2.25f;
    TimerComponent* timers_{nullptr};
    TimerHandle blinkHandle_{};
    CooldownHandle boostCooldown_{};
    bool highlight_{false};
    bool boosting_{false};
};

class GameScene final : public Scene, public HasDebugOverlay {
public:
    explicit GameScene(Runtime& r) :
        Scene(r) {}

    void enter() override {
        // Load background and player sprite generated by Python helpers.
        auto& bgTex = assets().loadTexture("background", "../examples/basic_game/assets/background.bmp");
        auto& playerTex = assets().loadTexture("player", "../examples/basic_game/assets/player.bmp");

        auto const size = runtime().window().size();
        camera_ = rlge::Camera2DController();
        camera_.setOffset({size.x * 0.5f, size.y * 0.5f});
        setSingleView(camera_);

        // Draw order: background first, player on top.
        bg_  = &spawn<Background>(bgTex);
        example_entity_ = &spawn<ExampleEntity>(playerTex);
        fps_ = &spawn<FpsCounter>();

        sceneToggleHandle_ = timers().every(1.25f, 6, [this] {
            if (bg_)
                bg_->visible_ = !bg_->visible_;
            sceneToggleCount_++;
        });

        globalHeartbeatHandle_ = runtime().services().timers().every(2.0f, [this] { globalHeartbeat_++; });
    }

    void update(float dt) override {
        Scene::update(dt);
        // Make the camera follow the player entity.
        if (const auto* view = primaryView()) {
            if (const auto* tr = example_entity_->get<rlge::Transform>()) {
                view->camera.get().follow(tr->position);
            }
        }
    }

    void exit() override {
        if (globalHeartbeatHandle_)
            globalHeartbeatHandle_.cancel();
        Scene::exit();
    }

    void debugOverlay() override {
        ImGui::Begin("Game debug");
        ImGui::Text("Number of entities: %d", static_cast<int>(entities().size()));

        // Render performance stats
        const auto& stats = rq().stats();
        ImGui::Separator();
        ImGui::Text("Render Performance:");
        ImGui::Text("  Sprites: %zu", stats.spritesSubmitted);
        ImGui::Text("  Batches: %zu", stats.batchCount);
        ImGui::Text("  Prepared Draw Calls: %zu", stats.drawCalls);
        ImGui::Text("  Executed Draw Calls: %zu", stats.executedDrawCalls);
        ImGui::Text("  Views Rendered: %zu", stats.viewsRendered);
        ImGui::Text("  Custom Cmds: %zu", stats.customCommands);
        ImGui::Text("  Sort Time: %.3f ms", stats.sortTimeMs);
        ImGui::Text("  Flush Time: %.3f ms", stats.flushTimeMs);
        ImGui::Separator();

        if (bg_) {
            ImGui::Checkbox("Show background", &bg_->visible_);
        }

        if (example_entity_) {
            if (auto* tr = example_entity_->get<rlge::Transform>()) {
                ImGui::SliderFloat("Player X", &tr->position.x, -500.f, 500.f);
                ImGui::SliderFloat("Player Y", &tr->position.y, -500.f, 500.f);
                ImGui::SliderFloat("Player rotation", &tr->rotation, 0.f, 360.f);
            }
            ImGui::Text(
                "Entity timer blinking: %s", example_entity_->highlighting() ? "ON" : "off"
            );
            ImGui::Text(
                "Boost cooldown ready: %s", example_entity_->boostReady() ? "yes" : "charging"
            );
            ImGui::Text("Boosting active: %s", example_entity_->boosting() ? "yes" : "no");
            ImGui::SliderFloat("Base speed", &example_entity_->baseSpeed_, 50.f, 600.f);
            ImGui::SliderFloat("Boost multiplier", &example_entity_->boostMultiplier_, 1.2f, 4.0f);
        }

        ImGui::Separator();
        ImGui::Text("Scene timer toggles: %d / 6", sceneToggleCount_);
        ImGui::Text("Global timer heartbeats: %d", globalHeartbeat_);
        ImGui::End();
    }
private:
    Background* bg_{nullptr};
    ExampleEntity* example_entity_{nullptr};
    rlge::Camera2DController camera_;
    FpsCounter* fps_{nullptr};
    TimerHandle sceneToggleHandle_{};
    TimerHandle globalHeartbeatHandle_{};
    int sceneToggleCount_{0};
    int globalHeartbeat_{0};
};

int main() {
    WindowConfig cfg{
        .width = 960,
        .height = 540,
        .fps = 60,
        .title = "RLGE Basic Game"
    };
    Runtime runtime(cfg);

    // Basic input bindings using type-safe enums
    runtime.input().bind(rlge::Action::MoveLeft, rlge::KeyCode::A);
    runtime.input().bind(rlge::Action::MoveRight, rlge::KeyCode::D);
    runtime.input().bind(rlge::Action::MoveUp, rlge::KeyCode::W);
    runtime.input().bind(rlge::Action::Fire, rlge::KeyCode::Space);

    // Start with our game scene
    runtime.pushScene<GameScene>();
    runtime.run();

    return 0;
}
