#include <print>

#include "debug.hpp"
#include "runtime.hpp"
#include "window.hpp"
#include "imgui.h"
#include "sprite.hpp"
#include "transformer.hpp"
#include "render_entity.hpp"

using namespace rlge;

class FpsCounter final : public RenderEntity {
public:
    explicit FpsCounter(Scene& scene) : RenderEntity(scene) {}

    void draw() override {
        rq().submitUI([] {
            DrawFPS(10, 10);
        });
    }
};
// Background entity that draws a wide patterned image so movement is obvious.
class Background final : public RenderEntity {
public:
    explicit Background(Scene& scene, Texture2D& texture)
        : RenderEntity(scene)
        , texture_(texture) {}

    void draw() override {
        if (!visible_)
            return;
        // Draw at world origin; the camera moving will reveal different parts.
        rq().submitBackground([this] {
            DrawTexture(texture_, 0, 0, WHITE);
        });
    }

private:
    Texture2D& texture_;
    bool visible_ = true;

    friend class GameScene;
};

// Simple player entity that can move left/right/rotate and is followed by the camera.
class ExampleEntity final : public RenderEntity {
public:
    explicit ExampleEntity(Scene& scene, Texture2D& texture)
        : RenderEntity(scene) {
        auto& tr = add<rlge::Transform>();
        tr.position = {100.0f, 200.0f};

        auto& anim = add<SpriteAnim>(texture, 32, 32);
        anim.loadStrip(0, 4, 0.15f);
    }

    void update(float dt) override {
        Entity::update(dt);

        const auto& input = scene().input();

        auto* tr = get<rlge::Transform>();
        if (!tr)
            return;

        if (input.down("left"))
            tr->position.x -= speed_ * dt;
        if (input.down("right"))
            tr->position.x += speed_ * dt;
        if (input.down("up"))
            tr->rotation += speed_ * dt;
    }

    float speed_ = 200.0f;

    friend class GameScene;
};

class GameScene final : public Scene, public HasDebugOverlay {
public:
    explicit GameScene(Runtime& r) :
        Scene(r) {}

    void enter() override {
        // Load background and player sprite generated by Python helpers.
        auto& bgTex = assets().loadTexture("background", "../examples/basic_game/assets/background.bmp");
        auto& playerTex = assets().loadTexture("player", "../examples/basic_game/assets/player.bmp");

        camera_ = rlge::Camera();
        setSingleView(camera_);

        // Draw order: background first, player on top.
        bg_  = &spawn<Background>(bgTex);
        example_entity_ = &spawn<ExampleEntity>(playerTex);
        fps_ = &spawn<FpsCounter>();
    }

    void update(float dt) override {
        Scene::update(dt);
        // Make the camera follow the player entity.
        if (const auto* view = primaryView()) {
            if (const auto* tr = example_entity_->get<rlge::Transform>()) {
                view->camera->follow(tr->position);
            }
        }
    }

    void debugOverlay() override {
        ImGui::Begin("Game debug");
        ImGui::Text("Number of entities: %d", static_cast<int>(entities().size()));

        // Render performance stats
        const auto& stats = rq().stats();
        ImGui::Separator();
        ImGui::Text("Render Performance:");
        ImGui::Text("  Sprites: %zu", stats.spritesSubmitted);
        ImGui::Text("  Batches: %zu", stats.batchCount);
        ImGui::Text("  Draw Calls: %zu", stats.drawCalls);
        ImGui::Text("  Custom Cmds: %zu", stats.customCommands);
        ImGui::Text("  Sort Time: %.3f ms", stats.sortTimeMs);
        ImGui::Text("  Flush Time: %.3f ms", stats.flushTimeMs);
        ImGui::Separator();

        if (bg_) {
            ImGui::Checkbox("Show background", &bg_->visible_);
        }

        if (example_entity_) {
            if (auto* tr = example_entity_->get<rlge::Transform>()) {
                ImGui::SliderFloat("Player X", &tr->position.x, -500.f, 500.f);
                ImGui::SliderFloat("Player Y", &tr->position.y, -500.f, 500.f);
                ImGui::SliderFloat("Player rotation", &tr->rotation, 0.f, 360.f);
            }
            ImGui::SliderFloat("Player speed", &example_entity_->speed_, 50.f, 600.f);
        }
        ImGui::End();
    }
private:
    Background* bg_{nullptr};
    ExampleEntity* example_entity_{nullptr};
    rlge::Camera camera_;
    FpsCounter* fps_{nullptr};
};

int main() {
    WindowConfig cfg{
        .width = 960,
        .height = 540,
        .fps = 60,
        .title = "RLGE Basic Game"
    };
    Runtime runtime(cfg);

    // Basic input bindings
    runtime.input().bind("left", KEY_A);
    runtime.input().bind("right", KEY_D);
    runtime.input().bind("up", KEY_W);

    // Start with our game scene
    runtime.pushScene<GameScene>();
    runtime.run();

    return 0;
}
